In [1]:
import numpy as np

In [3]:
arr=np.random.randint(0,100 , 10)

In [4]:
arr

array([58, 11, 51,  3, 41,  9, 62, 27, 33, 30])

In [5]:
arr[8]

33

In [7]:
arr[1:5]

array([11, 51,  3, 41])

In [8]:
arr[:6]

array([58, 11, 51,  3, 41,  9])

In [9]:
arr[5:]

array([ 9, 62, 27, 33, 30])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   9,  62,  27,  33,  30])

In [16]:
arr=np.arange(10+1)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr=arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]=99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy=arr.copy()

In [25]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:]=100

In [32]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr[[0,3,4,5
    ]]

array([99, 99, 99, 99])

# matrix

In [30]:
mat=np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])

In [31]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
mat[0]

array([ 5, 10, 15])

In [37]:
mat[1,1]

25

In [38]:
mat[1][1]

25

In [39]:
mat[2][1]

40

In [40]:
mat[1,]

array([20, 25, 30])

In [41]:
mat[1,2]

30

# Row and Column selection

In [44]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [45]:
mat[:2 , :-1]

array([[ 5, 10],
       [20, 25]])

In [46]:
mat[:2 , :2]

array([[ 5, 10],
       [20, 25]])

In [47]:
mat[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [48]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
mat[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [50]:
mat[1: , 1:]

array([[25, 30],
       [40, 45]])

In [51]:
mat[1: , :-1]

array([[20, 25],
       [35, 40]])

# Boolean array

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr=np.random.randint(0,100, 10)

In [55]:
arr

array([77, 68, 76, 13,  1, 30, 57, 91, 64, 92])

In [57]:
bool_arr=arr> 90

In [58]:
bool_arr

array([False, False, False, False, False, False, False,  True, False,
        True])

In [59]:
arr[bool_arr]

array([91, 92])

In [62]:
arr[arr> 60]

array([77, 68, 76, 91, 64, 92])

In [63]:
arr[arr<50]

array([13,  1, 30])

In [64]:
arr[arr>90]

array([91, 92])

# Exercise 

In [65]:
arr_2d=np.arange(50).reshape(5,10)

In [67]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
arr_2d[1:3 , 3:5]

array([[13, 14],
       [23, 24]])

In [71]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])