In [1]:
import numpy as np           

In [14]:
arr=np.array([1,2,3,4,5] , dtype=np.int8)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
arr[1]

2

In [5]:
arr[[2,3,4]]

array([3, 4, 5], dtype=int8)

In [6]:
my_list=[1,2,3,4]


In [7]:
my_list

[1, 2, 3, 4]

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
my_maths=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])



In [15]:
my_maths.ndim

2

In [16]:
a=np.array(3)

In [18]:
a.ndim

0

#arange

In [20]:
digits=np.arange(1,10)

In [21]:
digits

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
even_digits=np.arange(0,11,2)

In [27]:
even_digits

array([ 0,  2,  4,  6,  8, 10])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [38]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# To make an identity matrix:

In [15]:
#To make an identity matrix:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(2 , dtype=np.int8)

array([[1, 0],
       [0, 1]], dtype=int8)

# To create an array of random numbers:

In [17]:
#To create an array of random numbers:

np.random.rand(5)

array([0.57205557, 0.95454119, 0.9520067 , 0.87232909, 0.82230132])

In [18]:
np.random.rand(5,5)

array([[0.55540834, 0.99053276, 0.45778145, 0.35710374, 0.45892815],
       [0.44911964, 0.45376128, 0.4403912 , 0.48124038, 0.54440297],
       [0.20504341, 0.75826738, 0.51661798, 0.95090162, 0.5795109 ],
       [0.36105452, 0.15309108, 0.0188033 , 0.32214295, 0.1461404 ],
       [0.47100009, 0.86840817, 0.45471455, 0.99114226, 0.51974421]])

In [19]:
np.random.randn(2)

array([-0.75968152,  1.65634707])

In [21]:
np.random.randn(2,2)

array([[-2.18302382,  1.41266205],
       [-1.45028719, -0.18774988]])

In [22]:
np.random.randint(1,100)

89

In [23]:
np.random.randint(1,100,10)

array([29, 83, 46, 31, 65, 43, 21, 46, 90,  2])

# reshape

In [25]:
arr=np.arange(0,25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
rnarr=np.random.randint(0,100 , 10)

# methods

In [29]:
rnarr

array([13, 90, 74, 23, 70, 97, 74, 73, 21, 15])

In [31]:
rnarr.max()

97

In [33]:
rnarr.min() 

13

In [34]:
rnarr.argmax()

5

In [35]:
rnarr.argmin()

0

In [38]:
rnarr.shape

(10,)

In [39]:
rnarr.dtype

dtype('int32')